server:
  port: 8094

# 线程池配置
thread:
  pool:
    executor:
      config:
        core-pool-size: 15
        max-pool-size: 40
        keep-alive-time: 5000
        block-queue-size: 3000
        policy: CallerRunsPolicy

atluofu:
  dynamic:
    thread-pool:
      enabled: true
      app-name: ${spring.application.name}
      instance-id: ${spring.application.name}-${server.port}
      registry:
        type: redis
        redis:
          host: 127.0.0.1
          port: 6379
          password: HomeLab666
          database: 0
      report:
        enabled: true
        interval: 20s
      trace:
        enabled: true
        mdc-enabled: true
        trace-id-key: traceId
        request-id-key: requestId
      virtual:
        enabled: true
        default-concurrency-limit: 500

# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml
